// noinspection SpellCheckingInspection

exports.SupportedDevices = {
    "vi829v": {
        "name": "DEEBOT OZMO 920",
        "deviceClassLink": "yna5xi"
    },
    "x5d34r": {
        "name": "DEEBOT OZMO T8 AIVI",
        "deviceClassLink": "h18jkh"
    },
    "2o4lnm": {
        "name": "DEEBOT X1 TURBO",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X1"
    },
    "sdp1y1": {
        "name": "AIRBOT Z1",
        "950type": true,
        "950type_V2": true,
        "clean_speed": true,
        "spot_area": true,
        "map_image_supported": false,
        "yiko": true,
        "type": "airbot"
    },
    "20anby": {
        "name": "Z1 Air Quality Monitor",
        "950type": true,
        "950type_V2": true,
        "type": "aqMonitor"
    },
    "99fqkn": {
        "name": "Z1 Air Quality Monitor",
        "950type": true,
        "950type_V2": true,
        "type": "aqMonitor"
    }
};

exports.KnownDevices = {
    "123": {
        "name": "DEEBOT Slim2 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": false,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": false,
        "custom_area": false,
        "mopping_system": false,
        "voice_report": false,
        "auto_empty_station": false,
        "clean_speed": false,
        "map_image_supported": false,
        "type": "legacy"
    },
    "126": {
        "name": "DEEBOT N79",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "02uwxm": {
        "name": "DEEBOT OZMO Slim10 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": false,
        "side_brush": true,
        "filter": true,
        "mopping_system": true,
        "voice_report": false,
        "clean_speed": true,
        "type": "legacy"
    },
    "vsc5ia": {
        "name": "DEEBOT 500",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "dl8fht": {
        "name": "DEEBOT 600 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "130": {
        "name": "DEEBOT OZMO 610 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "mopping_system": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "uv242z": {
        "name": "DEEBOT 710",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "voice_report": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "ls1ok3": {
        "name": "DEEBOT 900 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "legacy"
    },
    "y79a7u": {
        "name": "DEEBOT OZMO 900 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "2pv572": {
        "name": "DEEBOT OZMO 905",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "type": "legacy"
    },
    "115": {
        "name": "DEEBOT OZMO/PRO 930 Series",
        "950type": false,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "map_image_supported": true,
        "type": "legacy"
    },
    "yna5xi": {
        "name": "DEEBOT OZMO 950 Series",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "950"
    },
    "h18jkh": {
        "name": "DEEBOT OZMO T8",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "T8"
    },
    "ucn2xe": {
        "name": "DEEBOT T9",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "air_freshener_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "T9"
    },
    "8kwdb4": {
        "name": "DEEBOT T9 AIVI",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "T9"
    },
    "n6cwdb": {
        "name": "DEEBOT N8",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": false,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "N8"
    },
    "jtmf04": {
        "name": "DEEBOT T10",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "T10"
    },
    "rss8xk": {
        "name": "DEEBOT T10 PLUS",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": false,
        "air_freshener_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "T10"
    },
    "9s1s80": {
        "name": "DEEBOT T10 TURBO",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "T10"
    },
    "lx3j7m": {
        "name": "DEEBOT T10 OMNI",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "T10"
    },
    "p1jij8": {
        "name": "DEEBOT T20 OMNI",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "T20"
    },
    "3yqsch": {
        "name": "DEEBOT X1",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X1"
    },
    "8bja83": {
        "name": "DEEBOT X1 Omni",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X1"
    },
    "n4gstt": {
        "name": "DEEBOT X1 PLUS",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": false,
        "air_freshener_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X1"
    },
    "e6ofmn": {
        "name": "DEEBOT X2",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": false,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X2"
    },
    "p7l7iu": {
        "name": "DEEBOT X2 OMNI Height",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "air_drying": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "hosted_mode": true,
        "yiko": true,
        "type": "X2"
    },
    "ipzjy0": {
        "name": "DEEBOT U2",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "type": "U2"
    },
    "h041es": {
        "name": "yeedi vac hybrid",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "mnx7f4": {
        "name": "yeedi vac station",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "aaxesz": {
        "name": "yeedi vac 2 pro",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "04z443": {
        "name": "yeedi vac max",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "p5nx9u": {
        "name": "yeedi 2 hybrid",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": false,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "vthpeg": {
        "name": "yeedi mop station",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": true,
        "round_mop_info": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "air_drying": true,
        "voice_report": true,
        "auto_empty_station": false,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "6r6dbt": {
        "name": "yeedi cube",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "9t30w8": {
        "name": "yeedi vac 2",
        "950type": true,
        "950type_V2": false,
        "main_brush": true,
        "side_brush": true,
        "filter": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": true,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "yeedi"
    },
    "5xu9h3": {
        "name": "GOAT G1",
        "950type": true,
        "950type_V2": true,
        "type": "goat"
    }
};
