services:
  ecovacs:
    build: .
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    tty: true
    stdin_open: true
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=development
      - ECOVACS_ACCOUNT_ID
      - ECOVACS_PASSWORD
      - ECOVACS_DEVICE_NUMBER
      - ECOVACS_CLIENT_DEVICE_ID
      - ECOVACS_DEVICE_ID # deprecated alias for ECOVACS_CLIENT_DEVICE_ID
      - ECOVACS_COUNTRY_CODE
      - ECOVACS_AUTH_DOMAIN
    command: node example/app.js
